### ISSUE TITLE
Create community UI for DataPerf

### ISSUE THREAD

**Issue by remg1997** [mlcommons/dynabench#145]

**Comment by Ciroye** [comment]
- [ ] Create landing page 

- [ ] Charge the tasks associated with this community

- [ ] Generation of transitions between task loading period

- [ ] Verify the behavior of "trends

**Comment by Ciroye** [comment]
- [ ] Create new endpoint for dynaboard information

- [ ] Re factoring leader board component

- [ ] Dynamically calculates Dynaboard information as weights change
