### ISSUE TITLE
Test new builder deployments

### ISSUE THREAD

**Issue by remg1997** [mlcommons/dynabench#146]
In order to create new tasks, ML models are being deployed twice: the first time on a server, to run heavy batch evaluation on the scoring datasets, and the second time on lambda, to get them 'in the loop' according to the create and validate sample use case. We are testing alternatives to make this process as easy and straightforward as possible for new task owners.

**Comment by remg1997** [comment]
- [ ] Light model deployment
- [ ] Heavy evaluation

**Comment by Ciroye** [comment]
- [ ] Checking the behavior of the model in the loop when creating a new sample
