### ISSUE TITLE
dynascore sorting bug

### ISSUE THREAD

**Issue by kawine** [mlcommons/dynabench#188]
When sorting by dynascore, there are a couple models that are out of place. For example, on the HateSpeech benchmark, Fasttext and T5 (default) are out of place in the Dynascore sort, with T5 (default) ranked as the best even though its dynascore is not the highest: https://dynabench.org/tasks/hs

**Comment by kawine** [comment]
On closer inspection, it seems that the leaderboard is actually sorting by the column to the left of Dynascore instead of Dynascore itself.

**Comment by Ciroye** [comment]
Solve it, it was effectively an error when ordered by dynascore, thanks
