### ISSUE TITLE
Is it possible to download the data?

### ISSUE THREAD

**Issue by MoritzLaurer** [mlcommons/dynabench#5]
I really like the project! I would be very interested in downloading some of the (NLI) data to build better (NLI) models that go beyond typical training data like MNLI and ANLI. Is it possible to download the dynamically created data somehow? If not, do you plan on making it downloadable at some point?
I found some data here, but nothing on NLI data: https://huggingface.co/dynabench

**Comment by douwekiela** [comment]
There has been some work there but it hasn't been released yet - feel free to ask Yixin Nie for more info!
