### ISSUE TITLE
Fix log download for each model

### ISSUE THREAD

**Issue by remg1997** [mlcommons/dynabench#88]
Each model card includes a download button to access the deployment logs. That button currently returns an empty log for all models

**Comment by TristanThrush** [comment]
Yeah, the log is supposed to come from the sagemaker batch transform job. This is especially useful if a handler crashed and the user wants to know why.

**Comment by remg1997** [comment]
The functionality seems to be working. Nevertheless, @douwekiela mentioned that there are many white spaces on the model card and some misaligned titles the could be made prettier.
