### ISSUE TITLE
Can't set dynalab 2.0 models in the data collection loop

### ISSUE THREAD

**Issue by TristanThrush** [mlcommons/dynabench#90]
I noticed that, for some reason, I can't put this model in the data collection loop for sentiment: https://dynabench.org/models/633

The model's name doesn't appear here:
<img width="1512" alt="Screen Shot 2022-09-15 at 10 36 37 AM" src="https://user-images.githubusercontent.com/20826878/190472767-27f0f58b-cc3a-43fe-b6bc-073e1d6c7ed7.png">

**Comment by Ciroye** [comment]
fixed in the new implementation of the models
